### ISSUE TITLE
Lukning af UDK-sager (85.11.00-P20-20-22)

### ISSUE THREAD

**Issue by cbh-randers** [Randers-Kommune-Digitalisering/doc-arbejdsgangsbeskrivelser#26]
```[tasklist]
### Tasks
- [ ] https://github.com/Randers-Kommune-Digitalisering/doc-arbejdsgangsbeskrivelser/issues/27
- [ ] https://github.com/Randers-Kommune-Digitalisering/doc-arbejdsgangsbeskrivelser/issues/79
```

Risikovurdering er afsendt til Bent - afventer underskrift. 

Herudover undersøges det, hvorvidt filerne er opbevaret hos arkivet i Randers, da dette kan afhjælpe problematikken omkring sikkerhed. Herudover kan det evt. også fjerne arbejdsprocessen fra Dan.

**Comment by cbh-randers** [comment]
Under afklaring med RPA Danmark.

**Comment by tna-randers** [comment]
Er den i drift? @tna-randers

**Comment by cbh-randers** [comment]
Dan fortæller, at robotten er i drift og har overstået driftstest. 
Der er oprettet en proces i OS2Autoproces.
