### ISSUE TITLE
Kortlægning af arbejdsproces

### ISSUE THREAD

**Issue by cbh-randers** [Randers-Kommune-Digitalisering/doc-arbejdsgangsbeskrivelser#32]
Procesdiagram kan ses her: https://github.com/Randers-Kommune-Digitalisering/doc-arbejdsgangsbeskrivelser/tree/main/Overlevering%20af%20godkendelse%20af%20autorisationsanmodninger%20til%20SAP%20BO

**Comment by jmk-randers** [comment]
Arbejdsgang kortlagt og optegnet.
