### ISSUE TITLE
Afdækning af datakilder

### ISSUE THREAD

**Issue by jmk-randers** [Randers-Kommune-Digitalisering/doc-arbejdsgangsbeskrivelser#39]
Skabelon til registrering at mulige datakilder:

| Datakildenavn | Dataejer | evt. Leverandør | Datatype | Adgang/placering | Kvalitet/kommentar |
|---|---|---|---|---|---|
|CapaInstaller | Tim? | [Capasystems](https://www.capasystems.com/about-capasystems/) | Hardware/Base Software assets | ?? | |
| Opus Rakat | ??Indkøb PEter Lund Neumann | KMD | Faktura| |
| fk.org/adg | ?? | KOMBIT | Organisations forhold, brugerdata | ||
| lenovo | ?? | lenovo | Maskin indkøbsdata og garantiudløb | | |
| netværk ICE | Jan Møller | Netværksplaceringer og registreringer| ||
| Azure | ?? | Morten Knudsen/Microsoft | Maskinregistreringer(Azure Monitor) |||
| Mobile Iron | MDM team | Mobile Iron | Mobile devices | | |
| TDC-erhverv | Monica? | TDC | Mobilabonnementer | | |

## Behovsanalyse
1. Skal det bruges i projektsammenhæng? (eksempelvis årshjulet) - mere realtime data
2. Skal det bruges til at levere et overblik over ejerskab af udstyr til forvaltningerne?
3. OVerblik eller analyse over garanti periode
4. Skal det bruges i forbindelse med indkøbsanalyse / Life Cycle Management / klimaaftryk
5. Software Licensanalyse / rapportering?
6. Skal det primært bruges til daglige support formål (Ala "visinfo2" fra AD+Capa)
7. Skal det anvendes til overblik over infrastruktur (servere/netværk m.v.)

## Afgrænsning:
Som udgangspunkt er Asset Management disciplinen meget omfattende. Hardware/Devices, Software, Licenser, Abbonementer

Hardware er opdelt på det administrative og det pædagogiske net og det vil ikke være muligt at anvende samme datakilder og samme metoder til datarekvirering.

Chromebooks er registreret for sig selv og kan ikke slåes op på samme måde.

Assets er **ikke** data indholdt i Identity and Access management (identiteter, adgange, roller og tilhørende)

En afgrænsning og opdeling kunne se sådan her ud:

Fase 1. Bærbare og stationære computere.

Senere faser kunne indsamle: Mobile devices, tilhørende abbonementer, software, tilhørende licenser.

**Comment by jmk-randers** [comment]
Databehov med udgangspunkt i årshjulprojektet:

1. Hardware information på stationære og bærbare computere (fra Capa)
2. Teknisk anvender (logon bruger)-->
3. Brugerforhold e-mail, tlfnummer, afdeling, forvaltning
4. Ejerskabs forhold Forvaltning (EAN)
5. Fysisk lokation (adresser postnummer)-(evt. placering på netværk som udgangspunkt)

**Comment by jmk-randers** [comment]
Dataflow i dag Indkøb i Rakat --> Com2 --> Faktura --> Kunder og support (itsupport@randers.dk) --> navn på faktura sættes manuelt som rekvirent i TopDesk

Rakat--> ?? Com2 -->

Kan der laves øget dataregistrering på Rakat? (brugerforhold eller lign.. gerne id)

**Comment by cbh-randers** [comment]
Lars og Vibeke er enige i de afdækkede behov. Behov der skal prioriteres først: 
1. Skal det bruges i projektsammenhæng? (eksempelvis årshjulet) - mere realtime data
2. Skal det bruges til at levere et overblik over ejerskab af udstyr til forvaltningerne?
6. Skal det primært bruges til daglige support formål (Ala "visinfo2" fra AD+Capa)

Herudover er det blevet aftalt, at vi starter med punkt 1. 
Vibeke er koordinator og vi laver opstartsmøde, hvor vi får introduceret til Github og milestones.

**Comment by cbh-randers** [comment]
Rita har overtaget projektledelse på Projektet og derfor afsluttes den herfra i denne omgang.
