### ISSUE TITLE
Afholdelse af afstemningsmøde for opstart

### ISSUE THREAD

**Issue by jmk-randers** [Randers-Kommune-Digitalisering/doc-arbejdsgangsbeskrivelser#53]

**Comment by cbh-randers** [comment]
Lars og Vibeke er enige i de afdækkede behov. Behov der skal prioriteres først:

Skal det bruges i projektsammenhæng? (eksempelvis årshjulet) - mere realtime data
Skal det bruges til at levere et overblik over ejerskab af udstyr til forvaltningerne?
Skal det primært bruges til daglige support formål (Ala "visinfo2" fra AD+Capa)
Herudover er det blevet aftalt, at vi starter med punkt 1.
Vibeke er koordinator og vi laver opstartsmøde, hvor vi får introduceret til Github og milestones.

**Comment by cbh-randers** [comment]
Vibeke har koordineringen på det. Jeg indkalder til opstartsmøde.

**Comment by jmk-randers** [comment]
Opstartsmøde afholdt
