### ISSUE TITLE
Formulardata til SBSYS

### ISSUE THREAD

**Issue by cbh-randers** [Randers-Kommune-Digitalisering/doc-arbejdsgangsbeskrivelser#57]
UMT får en masse sager ind via webformularer (xflow). De ryger i en postkasse og opretter så selv SBSYS-sager. Sagen er dog den, at meget af det der står i formularerne, skal sagsbehandlerne selv taste ind bagefter, fordi dokumenterne er simple pdf-er (og altså ikke data)

**Comment by jmk-randers** [comment]
Afventer afklaring med SBSYS integration

**Comment by tna-randers** [comment]
Sagen lukkes, da der ikke er konkrete forespørgsler.
