### ISSUE TITLE
Elektronisk signatur (85.11.00-P20-31-23)

### ISSUE THREAD

**Issue by cbh-randers** [Randers-Kommune-Digitalisering/doc-arbejdsgangsbeskrivelser#82]
Beredskab og Sikkerhed har kontakt os via Topdesk. Det er interesserede i at undersøge mulighederne for elektronisk signatur. Der er tale om dokumenter, som skal underskrives af deres direktør (Morten Sønderby). På nuværende tidspunkt bliver dokumenterne underskrevet i hånden, hvilket giver utrolig mange flaskehalse, da Morten oftest er ude af huset og derfor kan dokumenterne ligge flere dage på kontoret, og dermed bremse processen for øvrige medarbejdere. 

Der er ønsker om, at Morten selv kan underskrive elektronisk, men ligeledes at hans administrative medarbejdere han underskrive dokumenter på vegne af ham (som han dog har godkendt førend). Dette vil give mere effektive arbejdsgange. 

OBS: Beredskab og Sikkerhed er et selvstændigt selskab, som består af fire kommuner. De har derfor andre beføjelser end kommunen. De bruger dog jurister fra kommunerne. Derudover har de en administrationsaftale med Randers Kommune, hvor de betaler for administrative ydelser. 
```[tasklist]
### Tasks
- [ ] Undersøg om det er juridisk i orden at underskrive med Adobe Reader
- [ ] Kan man købe sig til brug af underskrifter i Penneo?
```

**Comment by cbh-randers** [comment]
Efter behovsafklaringsmøde med Morten afholdt d. 15-11-2023 undersøges følgende af undertegnede: 
- Kan Adobe Reader bruges? Juridiske aspekt? 
- Kan man købe sig underskrifter af Penneo? 

Jeg har sendt guide til Morten, som han selv vil kigge ind i. 

Han underskriver i gennemsnit dokumenter et par gange om ugen, og det er mange forskellige slags. Det er dog dokumenter, som skal underskrives af Morten og ikke af eksterne.

**Comment by cbh-randers** [comment]
Morten er kontaktet omkring, at vi er igang med at undersøge Penneo. Derudover har jeg sendt ham guide til Adobe, som de skal forholde sig til internt om de kan bruge. 

Den er lukket for nu.,

**Comment by tna-randers** [comment]
Behovsafklaringen viste ikke et stort behov. Derfor er det besluttet at anbefale at benytte Penneo, som Randers Kommune i forvejen benytter.
